apiVersion: v1
kind: ConfigMap
metadata:
  name: scadabr-jvm
  namespace: scada-minidash
data:
  setenv.sh: |
    #!/bin/sh

    export CATALINA_OPTS="-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Duser.timezone=America/Sao_Paulo"

