apiVersion: apps/v1
kind: Deployment
metadata:
  name: scadabr
  namespace: scada-minidash
spec:
  replicas: 1

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: scadabr

  template:
    metadata:
      labels:
        app: scadabr
    spec:
      nodeSelector:
        role: scada-minidash

      containers:
        - name: scadabr
          image: luanmw/scadabr:1.2
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"

          readinessProbe:
            httpGet:
              path: /ScadaBR/index.jsp
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /ScadaBR/index.jsp
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: scadabr-uploads
              mountPath: /usr/local/tomcat/webapps/ScadaBR/uploads

            - name: scadabr-env
              mountPath: /usr/local/tomcat/webapps/ScadaBR/WEB-INF/classes/env.properties
              subPath: env.properties

            - name: scadabr-jvm
              mountPath: /usr/local/tomcat/bin/setenv.sh
              subPath: setenv.sh

      volumes:
        - name: scadabr-uploads
          persistentVolumeClaim:
            claimName: scadabr-uploads

        - name: scadabr-env
          configMap:
            name: scadabr-env

        - name: scadabr-jvm
          configMap:
            name: scadabr-jvm
            defaultMode: 0755


