# mysql-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: scada-minidash
data:
  my.cnf: |
    [mysqld]
    innodb_buffer_pool_size = 256M
    innodb_log_file_size = 64M
    innodb_flush_log_at_trx_commit = 2

    max_connections = 50

    tmp_table_size = 64M
    max_heap_table_size = 64M

    table_open_cache = 400

    query_cache_type = 0
    query_cache_size = 0

    performance_schema = OFF

    datadir=/var/lib/mysql/data

